#!/bin/bash
# Nova — Interactive .env Setup Wizard
# Generates cryptographic secrets automatically. Run before deploy.sh.
# Usage: cd /opt/nova && bash deploy/setup-env.sh
set -euo pipefail

NOVA_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$NOVA_DIR"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()   { echo -e "${GREEN}[setup-env]${NC} $*"; }
warn()   { echo -e "${YELLOW}[setup-env] WARN:${NC} $*"; }
prompt() { echo -e "${CYAN}$*${NC}"; }

[[ -f ".env.example" ]] || { echo "ERROR: .env.example not found"; exit 1; }
command -v openssl &>/dev/null || { echo "ERROR: openssl not found"; exit 1; }

if [[ -f ".env" ]]; then
    warn ".env already exists."
    read -rp "Overwrite it? [y/N] " OVERWRITE
    [[ "${OVERWRITE,,}" == "y" ]] || { info "Aborted — existing .env preserved."; exit 0; }
fi

echo ""
echo "  Nova .env Configuration Wizard"
echo "  ─────────────────────────────────────────────"
echo "  Secrets will be generated automatically."
echo "  Press Enter to use the default shown in [brackets]."
echo ""

# ── Domain ────────────────────────────────────────────────────────────────────
prompt "Domain name for Nova (e.g. nova.example.com):"
read -rp "> " DOMAIN
[[ -n "$DOMAIN" ]] || { echo "ERROR: Domain is required."; exit 1; }

prompt "Email for Let's Encrypt certificate notifications:"
read -rp "> " CERTBOT_EMAIL
[[ -n "$CERTBOT_EMAIL" ]] || { echo "ERROR: Email is required."; exit 1; }

# ── Database ──────────────────────────────────────────────────────────────────
echo ""
prompt "PostgreSQL password (Enter to auto-generate):"
read -rp "> " POSTGRES_PASSWORD
if [[ -z "$POSTGRES_PASSWORD" ]]; then
    POSTGRES_PASSWORD=$(openssl rand -hex 24)
    info "Generated PostgreSQL password: $POSTGRES_PASSWORD"
elif [[ "$POSTGRES_PASSWORD" =~ [@:/] ]]; then
    echo "ERROR: Password cannot contain @, : or / — these break the DATABASE_URL. Use auto-generate or choose a safe password."; exit 1
fi

# ── Redis ─────────────────────────────────────────────────────────────────────
prompt "Redis password (Enter to auto-generate):"
read -rp "> " REDIS_PASSWORD
if [[ -z "$REDIS_PASSWORD" ]]; then
    REDIS_PASSWORD=$(openssl rand -hex 24)
    info "Generated Redis password: $REDIS_PASSWORD"
elif [[ "$REDIS_PASSWORD" =~ [@:/] ]]; then
    echo "ERROR: Password cannot contain @, : or / — these break the REDIS_URL. Use auto-generate or choose a safe password."; exit 1
fi

# ── App secrets (always auto-generated) ──────────────────────────────────────
SECRET_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
CELERY_HMAC_SECRET=$(openssl rand -hex 32)
info "Generated SECRET_KEY, JWT_SECRET, CELERY_HMAC_SECRET"

# ── Metasploit Pro (optional) ─────────────────────────────────────────────────
echo ""
prompt "Metasploit Pro RPC host (Enter to skip):"
read -rp "> " METASPLOIT_RPC_HOST
METASPLOIT_RPC_PASSWORD=""
if [[ -n "$METASPLOIT_RPC_HOST" ]]; then
    prompt "Metasploit Pro RPC password:"
    read -rp "> " METASPLOIT_RPC_PASSWORD
fi

# ── Titanux integration (optional) ───────────────────────────────────────────
prompt "Titanux URL for export push (Enter to skip):"
read -rp "> " TITANUX_URL
TITANUX_API_KEY=""
if [[ -n "$TITANUX_URL" ]]; then
    prompt "Titanux API key:"
    read -rp "> " TITANUX_API_KEY
fi

# ── Write .env ────────────────────────────────────────────────────────────────
cat > .env << EOF
# ─────────────────────────────────────────────────────────
#  Nova — Production Environment
#  Generated by deploy/setup-env.sh
#  DO NOT commit this file to version control.
# ─────────────────────────────────────────────────────────

# PostgreSQL
POSTGRES_DB=nova
POSTGRES_USER=nova
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# App secrets
SECRET_KEY=${SECRET_KEY}
JWT_SECRET=${JWT_SECRET}
CELERY_HMAC_SECRET=${CELERY_HMAC_SECRET}

# Metasploit Pro RPC (leave blank if not using)
METASPLOIT_RPC_HOST=${METASPLOIT_RPC_HOST}
METASPLOIT_RPC_PORT=55553
METASPLOIT_RPC_PASSWORD=${METASPLOIT_RPC_PASSWORD}

# Titanux integration (optional — for export push)
TITANUX_URL=${TITANUX_URL}
TITANUX_API_KEY=${TITANUX_API_KEY}

# Deployment
DOMAIN=${DOMAIN}
CERTBOT_EMAIL=${CERTBOT_EMAIL}
ENVIRONMENT=production
FRONTEND_BUILD_TARGET=production
EOF

chmod 600 .env
info ".env written and permissions set to 600"

echo ""
echo "  Next steps:"
echo "  1. Issue TLS certificate:   sudo bash deploy/init-certs.sh"
echo "  2. Launch Nova:             bash deploy/deploy.sh"
echo ""
